[opener]
edit = { run = 'nvim "$@"', block = true, desc = "Edit with nvim" }
finder = { run = 'open -R "$@"', desc = "Reveal in Finder" }

[open]
# Text files
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "application/json", use = "edit" },
	{ mime = "application/x-yaml", use = "edit" },
	{ mime = "application/toml", use = "edit" },
	{ name = "*.md", use = "edit" },
	{ name = "*.txt", use = "edit" },
	{ name = "*.conf", use = "edit" },
	{ name = "*.ini", use = "edit" },
	{ name = "*.yaml", use = "edit" },
	{ name = "*.yml", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.json", use = "edit" },
	{ name = "*.js", use = "edit" },
	{ name = "*.ts", use = "edit" },
	{ name = "*.py", use = "edit" },
	{ name = "*.sh", use = "edit" },
	{ name = "*.fish", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.rs", use = "edit" },
	{ name = "*.go", use = "edit" },
]

